CREATE TABLE IF NOT EXISTS "session" (
   "sid" varchar NOT NULL COLLATE "default",
   "sess" json NOT NULL,
   "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

CREATE TABLE IF NOT EXISTS consumer (
    mail_consumer VARCHAR(255) PRIMARY KEY,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    blood_group VARCHAR(3) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    password_user VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS admin (
    mail_admin VARCHAR(255) PRIMARY KEY,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    password_admin VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS hospital (
    hospital_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    mail VARCHAR(255) NOT NULL,
    phone_number VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS comment (
    comment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text_comment TEXT NOT NULL,
    mail_consumer VARCHAR(255) NOT NULL,
    date_publication timestamp NOT NULL DEFAULT now(),
    FOREIGN KEY(mail_consumer) REFERENCES consumer(mail_consumer) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointment (
    mail_consumer VARCHAR(255),
    hospital_id INT,
    date_appointment DATE NOT NULL,
    type_appointment VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    information VARCHAR(255),
    PRIMARY KEY (mail_consumer, hospital_id, date_appointment),
    FOREIGN KEY(mail_consumer) REFERENCES consumer(mail_consumer) ON DELETE CASCADE,
    FOREIGN KEY(hospital_id) REFERENCES hospital(hospital_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blood_bag (
    id VARCHAR(255) PRIMARY KEY,
    hospital_id INT NOT NULL,
    blood_group VARCHAR(3) NOT NULL,
    date_donation DATE NOT NULL,
    reserved BOOLEAN NOT NULL,
    FOREIGN KEY(hospital_id) REFERENCES hospital(hospital_id) ON DELETE CASCADE
);