CREATE TABLE IF NOT EXISTS "session" (
   "sid" varchar NOT NULL COLLATE "default",
   "sess" json NOT NULL,
   "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

CREATE TABLE IF NOT EXISTS utilisateur (
    mail_user VARCHAR(255) PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    groupe_sanguin VARCHAR(3) NOT NULL,
    genre VARCHAR(20) NOT NULL,
    adresse VARCHAR(255) NOT NULL,
    ville VARCHAR(255) NOT NULL,
    telephone VARCHAR(10) NOT NULL,
    password_user VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS administrateur (
    mail_admin VARCHAR(255) PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    telephone VARCHAR(10) NOT NULL,
    password_admin VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS hopital (
   hopital_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(50) NOT NULL,
   adresse VARCHAR(255) NOT NULL,
   mail VARCHAR(255) NOT NULL,
   telephone VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS commentaire (
    commentaire_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    texte TEXT NOT NULL,
    mail_user VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY(mail_user) REFERENCES utilisateur(mail_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rendez_vous (
    mail_user VARCHAR(255),
    hopital_id INT,
    date_rdv DATE NOT NULL,
    type_rdv VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    information VARCHAR(255),
    PRIMARY KEY (mail_user, hopital_id),
    FOREIGN KEY(mail_user) REFERENCES utilisateur(mail_user) ON DELETE CASCADE,
    FOREIGN KEY(hopital_id) REFERENCES hopital(hopital_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS poche_sang (
    mail_user VARCHAR(255),
    hopital_id INT,
    date_donnation DATE NOT NULL,
    PRIMARY KEY (mail_user, hopital_id),
    FOREIGN KEY(mail_user) REFERENCES utilisateur(mail_user) ON DELETE CASCADE,
    FOREIGN KEY(hopital_id) REFERENCES hopital(hopital_id) ON DELETE CASCADE
);
